server:
  port: 8080

movie:
  service:
    url: http://localhost:7070

spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/customer
    username: customer_user
    password: customer_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect